version: '3.8'

services:
  
  postgres_db:
    image: postgres:17
    environment: 
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - ../migrations/000001_init.up.sql:/docker-entrypoint-initdb.d/000001_init.up.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bug_tracker_network


  subscriptions_service_app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - postgres_db
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
    networks:
      - bug_tracker_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  bug_tracker_network:
    driver: bridge