DROP TABLE IF EXISTS bug_template;
DROP TABLE IF EXISTS bug_tag;
DROP TABLE IF EXISTS bug_relation;
DROP TABLE IF EXISTS audit_log;
DROP TABLE IF EXISTS bug_comment;
ALTER TABLE "User" DROP COLUMN IF EXISTS role;
